### PR TITLE
Update suryans@mulearn.md

### PR DESCRIPTION
**Pull request by suryan-s**
# Pull Request: Evaluation Criteria for Stage 3

## Introduction
This pull request proposes a new set of evaluation criteria for Stage 3, focusing on advanced aspects of software development. These criteria are designed to assess and foster innovation, community engagement, effective feedback reception, collaboration, domain-specific knowledge, and system design skills.

## Evaluation Criteria
Please review the following proposed criteria and check each box to indicate your review and agreement:

```
## Checklist:
Before you submit this pull request, please ensure you have completed the following items.

### Attitude and Values
- [ ] Feedback Reception: Openness to receiving feedback and making necessary improvements.
- [ ] Innovation: Attitude of thinking outside the box, coming up with novel solutions or approaches to problems.

### Abilities and Skills
- [ ] Collaboration: Skill in working within a team, understanding team dynamics, and contributing effectively.

### Knowledge and Information
- [ ] Domain-Specific Knowledge: Depending on the challenge, knowledge in areas like AI/ML, blockchain, game development, etc.
- [ ] System Design: Understanding of how to design scalable and efficient systems, including databases, servers, and client interactions.

### Other Criteria
- [ ] Has open source contributions

### Do you vouch for the top 100 coders?
- [ ] I vouch. You belong to the lead of Top 100 Coders 2023
- [ ] Good Job, All the best for the Top 100 Coders 2024
```

## Purpose
The purpose of these criteria is to provide a comprehensive and structured approach to evaluating advanced skills and contributions in software development, ensuring continuous improvement and excellence.

## How to Use
These criteria can be used for performance reviews, peer feedback, and self-assessment in advanced stages of software development roles.

---

Please review the proposed evaluation criteria for Stage 3 and check the corresponding boxes to indicate your review status, feedback, or approval. Your input is invaluable to ensure the criteria are robust and effective.

### CODE REVIEW

**Comment by Felixjosemon** [comment]
## Checklist:
Before you submit this pull request, please ensure you have completed the following items.

### Attitude and Values
- [x] Feedback Reception: Openness to receiving feedback and making necessary improvements.
- [x] Innovation: Attitude of thinking outside the box, coming up with novel solutions or approaches to problems.

### Abilities and Skills
- [ ] Collaboration: Skill in working within a team, understanding team dynamics, and contributing effectively.

### Knowledge and Information
- [x] Domain-Specific Knowledge: Depending on the challenge, knowledge in areas like AI/ML, blockchain, game development, etc.
- [x] System Design: Understanding of how to design scalable and efficient systems, including databases, servers, and client interactions.

### Other Criteria
- [x] Has open source contributions

### Do you vouch for the top 100 coders?
- [x] I vouch. You belong to the lead of Top 100 Coders 2023
- [x] Good Job, All the best for the Top 100 Coders 2024

**Comment by nhadiq** [comment]
## Checklist:
Before you submit this pull request, please ensure you have completed the following items.

### Attitude and Values
- [x] Feedback Reception: Openness to receiving feedback and making necessary improvements.
- [x] Innovation: Attitude of thinking outside the box, coming up with novel solutions or approaches to problems.

### Abilities and Skills
- [ ] Collaboration: Skill in working within a team, understanding team dynamics, and contributing effectively.

### Knowledge and Information
- [x] Domain-Specific Knowledge: Depending on the challenge, knowledge in areas like AI/ML, blockchain, game development, etc.
- [x] System Design: Understanding of how to design scalable and efficient systems, including databases, servers, and client interactions.

### Other Criteria
- [x] Has open source contributions

### Do you vouch for the top 100 coders?
- [ ] I vouch. You belong to the lead of Top 100 Coders 2023
- [x] Good Job, All the best for the Top 100 Coders 2024

**Review by bodhish — COMMENTED** [review]
## Checklist:
### Attitude and Values
- [x] Feedback Reception: Openness to receiving feedback and making necessary improvements.
- [x] Innovation: Attitude of thinking outside the box, coming up with novel solutions or approaches to problems.

### Abilities and Skills
- [x] Collaboration: Skill in working within a team, understanding team dynamics, and contributing effectively.

### Knowledge and Information
- [x] Domain-Specific Knowledge: Depending on the challenge, knowledge in areas like AI/ML, blockchain, game development, etc.
- [x] System Design: Understanding of how to design scalable and efficient systems, including databases, servers, and client interactions.

### Other Criteria
- [x] Has open source contributions

### Do you vouch for the top 100 coders?
- [x] I vouch. You belong to the lead of Top 100 Coders 2023
- [ ] Good Job, All the best for the Top 100 Coders 2024

**Comment by gigincg** [comment]
## Checklist:
Before you submit this pull request, please ensure you have completed the following items.

### Attitude and Values
- [x] Feedback Reception: Openness to receiving feedback and making necessary improvements.
- [x] Innovation: Attitude of thinking outside the box, coming up with novel solutions or approaches to problems.

### Abilities and Skills
- [x] Collaboration: Skill in working within a team, understanding team dynamics, and contributing effectively.

### Knowledge and Information
- [x] Domain-Specific Knowledge: Depending on the challenge, knowledge in areas like AI/ML, blockchain, game development, etc.
- [x] System Design: Understanding of how to design scalable and efficient systems, including databases, servers, and client interactions.

### Other Criteria
- [x] Has open source contributions

### Do you vouch for the top 100 coders?
- [x] I vouch. You belong to the lead of Top 100 Coders 2023
- [ ] Good Job, All the best for the Top 100 Coders 2024

**Comment by cskumaresan** [comment]
## Checklist:
Before you submit this pull request, please ensure you have completed the following items.

### Attitude and Values
- [x] Feedback Reception: Openness to receiving feedback and making necessary improvements.
- [x] Innovation: Attitude of thinking outside the box, coming up with novel solutions or approaches to problems.

### Abilities and Skills
- [ ] Collaboration: Skill in working within a team, understanding team dynamics, and contributing effectively.

### Knowledge and Information
- [x] Domain-Specific Knowledge: Depending on the challenge, knowledge in areas like AI/ML, blockchain, game development, etc.
- [x] System Design: Understanding of how to design scalable and efficient systems, including databases, servers, and client interactions.

### Other Criteria
- [x] Has open source contributions

### Do you vouch for the top 100 coders?
- [ ] I vouch. You belong to the lead of Top 100 Coders 2023
- [x] Good Job, All the best for the Top 100 Coders 2024

**Comment by alenpaulvarghese** [comment]
### Decisions - Pre Coding
 * [x]  Did they have a pre-planning involved, with discussions about the complexities involved and how to solve?
 * [x]  Can they reason their choice for selecting the tech stack used?
 
 
 ### Quality and Organization of Code
  * [x]  Is the code clean, readable, well-organized and maintainable?
  * [ ]  Does the variable and function names make sense?
  * [x]  Does the code adhere to best practices and standards? (structure, formatting, etc.)
  * [ ]  Are development best practices such as branching, merging, and pull requests well-utilized?
  * [ ]  Does the commit messages make sense?
 
 ### Authentication & Sanitization
 * [ ]  Does the project have a viable and secure authentication system in place?
 * [ ]  Are request parameters from the user sanitized before processing?

 ### Error Handling 
 * [ ]  Are the errors rescued and handled well?
 * [ ]  Do they have an error monitoring in place?
 * [ ]  For the user, are the errors conveyed in a senseful manner?
 
 
 ### Working as a team
 
* [ ]  Do the pull requests have apt title and description? Can the reviewer / team mate draw enough context from the pull request description?
* [ ]  Are the pull requests slim? i.e, not bloated, no unrelated changes in the same PR? Is the PR easy to review? 
* [ ]  Did they have a good mode of communication? How often were the communication between the team?
* [x]  Did they have documentation / scratch pads / brainstorming sessions with the team for features while building?
 
 
 ### Database
 
 * [ ]  Does the project have a DB schema?
 * [ ]  Can they reason why they chose this database? 
 * [ ]  Are adequate database validations in place? (Uniqueness or presence of emails for users etc.)
 * [ ]  If the database is hosted, how is the connection to the database established? Is it from inside a secure network?
 
 
 ### Scalability, Performance and Security Considerations 
 * [ ]  Can the solution scale effectively?
 * [ ]  Is the solution well-prepared for external API related issues (timeouts, rate limiting, errors)?
 * [ ]  Does the project adequately address security and data management practices, particularly in relation to data handling and storage?
* [x]  How are the tokens managed? Are any tokens exposed on client side or being committed into code?
 
 
 ### Overall Technical Excellence
 
 * [x]  Overall, does the technical aspect of the project and the coder stand out?
 
 ### Additional Feedback for Developers

- I think it's a great idea to summarise a topic by selecting the best video from Youtube.
- The number of videos should have been restricted to a small number because they are useless because the tokens would get sliced midway through the procedure.
- Should have tried to build a backend using OSS LLMs' as the project is really token-exhaustive.
 
 ### Do you vouch for the top 100 coders?
 
* [x]  I vouch. You belong to the lead of Top 100 Coders 2023
* [ ]  Good Job, All the best for the Top 100 Coders 2024

**Comment by bijoysijo** [comment]
### Decisions - Pre Coding
- [x] Did they have a pre-planning involved, with discussions about the complexities involved and how to solve?
- [x] Can they reason their choice for selecting the tech stack used?

### Quality and Organization of Code
- [ ] Is the code clean, readable, well-organized and maintainable?
- [ ] Does the variable and function names make sense?
- [ ] Does the code adhere to best practices and standards? (structure, formatting, etc.)
- [ ] Are development best practices such as branching, merging, and pull requests well-utilized?
- [ ] Does the commit messages make sense?

### Authentication & Sanitization
- [x] Does the project have a viable and secure authentication system in place?
- [ ] Are request parameters from the user sanitized before processing?

### Error Handling
- [x] Are the errors rescued and handled well?
- [ ] Do they have an error monitoring in place?
- [ ] For the user, are the errors conveyed in a senseful manner?

### Working as a team
- [ ] Do the pull requests have apt title and description? Can the reviewer / team mate draw enough context from the pull request description?
- [ ] Are the pull requests slim? i.e, not bloated, no unrelated changes in the same PR? Is the PR easy to review?
- [ ] Did they have a good mode of communication? How often were the communication between the team?
- [ ] Did they have documentation / scratch pads / brainstorming sessions with the team for features while building?

### Database (For backend projects or projects using Firebase)
- [ ] Does the project have a DB schema?
- [ ] Can they reason why they chose this database?
- [ ] Are adequate database validations in place? (Uniqueness or presence of emails for users etc.)
- [ ] If the database is hosted, how is the connection to the database established? Is it from inside a secure network?

### Scalability, Performance and Security Considerations (Data and Token Management for Backend Projects Only)
- [x] Can the solution scale effectively?
- [ ] Is the solution well-prepared for external API related issues (timeouts, rate limiting, errors)?
- [ ] Does the project adequately address security and data management practices, particularly in relation to data handling and storage?
- [ ] How are the tokens managed? Are any tokens exposed on client side or being committed into code?

### Overall Technical Excellence
- [x] Overall, does the technical aspect of the project and the coder stand out?

### Additional Feedback for Developers
> Please provide any additional feedback or observations

### Do you vouch for the top 100 coders?
- [ ] I vouch. You belong to the lead of Top 100 Coders 2023
- [ ] Good Job, All the best for the Top 100 Coders 2024

**Pull request merged**
